Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,20 +19,26 @@ jobs:
         run: |
           # HTML 내용 가져오기
           HTML=$(curl -s "http://${{ secrets.REACT_DOCKER_IP }}/healthcheck/env")
-
-          # 'blue' 값 추출하기 (class="env" 안의 텍스트 추출)
-          STATUS=$(echo "$HTML" | grep -oP '(?<=<div class="env">).*?(?=</div>)')
-
+      
+          # 'blue' 값 추출하기 (class="env"> 뒤의 값 가져오기)
+          STATUS=$(echo "$HTML" | sed -n 's/.*<div class="env">\([^<]*\)<\/div>.*/\1/p')
+      
           # 결과 출력
           echo "Extracted status: $STATUS"
-
+      
+          # 값이 비어있는 경우 오류 처리
+          if [ -z "$STATUS" ]; then
+            echo "Error: STATUS is empty"
+            exit 1
+          fi
+      
           # 'blue'에 따라서 조건 처리
           if [ "$STATUS" = "blue" ]; then
             echo "CURRENT_UPSTREAM=react_blue" >> $GITHUB_ENV
           else
             echo "CURRENT_UPSTREAM=react_green" >> $GITHUB_ENV
           fi
-
+      
           if [ "$CURRENT_UPSTREAM" = "react_blue" ]; then
             echo "CURRENT_PORT=3000" >> $GITHUB_ENV  
             echo "STOPPED_PORT=3001" >> $GITHUB_ENV
@@ -45,6 +51,7 @@ jobs:
             echo "Error: Invalid CURRENT_UPSTREAM"
             exit 1
           fi
+
 
       - name: Login to DockerHub
         uses: docker/login-action@v1
