Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,36 +22,71 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      # - name: Set target IP based on running Docker container
+      #   run: |
+      #     # 현재 실행 중인 컨테이너 확인
+      #     EXIST_BLUE=$(docker ps --filter "name=react_blue" --format "{{.Names}}")
+
+      #     # 실행 여부에 따라 CURRENT_UPSTREAM 결정
+      #     if [ -z "$EXIST_BLUE" ]; then
+      #       echo "react_blue is NOT running -> Setting CURRENT_UPSTREAM to react_blue"
+      #       CURRENT_UPSTREAM=react_blue
+      #     else
+      #       echo "react_blue is running -> Setting CURRENT_UPSTREAM to react_green"
+      #       CURRENT_UPSTREAM=react_green
+      #     fi
+
+      #     # GitHub 환경 변수 설정
+      #     echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+
+      #     if [ "$CURRENT_UPSTREAM" = "react_blue" ]; then
+      #       echo "CURRENT_PORT=3000" >> $GITHUB_ENV
+      #       echo "STOPPED_PORT=3001" >> $GITHUB_ENV
+      #       echo "TARGET_UPSTREAM=react_green" >> $GITHUB_ENV
+      #     elif [ "$CURRENT_UPSTREAM" = "react_green" ]; then
+      #       echo "CURRENT_PORT=3001" >> $GITHUB_ENV
+      #       echo "STOPPED_PORT=3000" >> $GITHUB_ENV
+      #       echo "TARGET_UPSTREAM=react_blue" >> $GITHUB_ENV
+      #     else
+      #       echo "error"
+      #       exit 1
+      #     fi
       - name: Set target IP based on running Docker container
-        run: |
-          # 현재 실행 중인 컨테이너 확인
-          EXIST_BLUE=$(docker ps --filter "name=react_blue" --format "{{.Names}}")
-
-          # 실행 여부에 따라 CURRENT_UPSTREAM 결정
-          if [ -z "$EXIST_BLUE" ]; then
-            echo "react_blue is NOT running -> Setting CURRENT_UPSTREAM to react_blue"
-            CURRENT_UPSTREAM=react_blue
-          else
-            echo "react_blue is running -> Setting CURRENT_UPSTREAM to react_green"
-            CURRENT_UPSTREAM=react_green
-          fi
-
-          # GitHub 환경 변수 설정
-          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
-
-          if [ "$CURRENT_UPSTREAM" = "react_blue" ]; then
-            echo "CURRENT_PORT=3000" >> $GITHUB_ENV
-            echo "STOPPED_PORT=3001" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=react_green" >> $GITHUB_ENV
-          elif [ "$CURRENT_UPSTREAM" = "react_green" ]; then
-            echo "CURRENT_PORT=3001" >> $GITHUB_ENV
-            echo "STOPPED_PORT=3000" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=react_blue" >> $GITHUB_ENV
-          else
-            echo "error"
-            exit 1
-          fi
-
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: ${{ secrets.REACT_DOCKER_IP }}
+          username: ${{ secrets.SSH_USER }}  # 예: 'ubuntu' 또는 EC2 사용자명
+          key: ${{ secrets.EC2_SSH_KEY }}
+          debug: true  # 디버그 메시지를 활성화
+          script: |
+            # 현재 실행 중인 컨테이너 확인
+            EXIST_BLUE=$(sudo docker ps --filter "name=react_blue" --format "{{.Names}}")
+      
+            # 실행 여부에 따라 CURRENT_UPSTREAM 결정
+            if [ -z "$EXIST_BLUE" ]; then
+              echo "react_blue is NOT running -> Setting CURRENT_UPSTREAM to react_blue"
+              CURRENT_UPSTREAM=react_blue
+            else
+              echo "react_blue is running -> Setting CURRENT_UPSTREAM to react_green"
+              CURRENT_UPSTREAM=react_green
+            fi
+      
+            # GitHub 환경 변수 설정
+            echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
+      
+            # 설정된 CURRENT_UPSTREAM에 따라 포트 및 TARGET_UPSTREAM 값 설정
+            if [ "$CURRENT_UPSTREAM" = "react_blue" ]; then
+              echo "CURRENT_PORT=3000" >> $GITHUB_ENV
+              echo "STOPPED_PORT=3001" >> $GITHUB_ENV
+              echo "TARGET_UPSTREAM=react_green" >> $GITHUB_ENV
+            elif [ "$CURRENT_UPSTREAM" = "react_green" ]; then
+              echo "CURRENT_PORT=3001" >> $GITHUB_ENV
+              echo "STOPPED_PORT=3000" >> $GITHUB_ENV
+              echo "TARGET_UPSTREAM=react_blue" >> $GITHUB_ENV
+            else
+              echo "error"
+              exit 1
+            fi
       - name: Build Docker
         run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/react_docker .
 
