Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -70,33 +70,32 @@ jobs:
             sudo docker-compose -f docker-compose-${{ env.TARGET_UPSTREAM }}.yml up -d
 
 
-      - name: Check if TARGET_UPSTREAM container is running
-        uses: appleboy/ssh-action@v0.1.10
-        with:
-          host: ${{ secrets.REACT_DOCKER_IP }}
-          username: ${{ secrets.SSH_USER }}  # EC2 사용자명 (예: ubuntu, ec2-user)
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            ATTEMPT=0
-            MAX_ATTEMPTS=3
-            RETRY_DELAY=10  # 10초 대기
-  
-            while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
-              echo "Attempt $((ATTEMPT+1)) - Checking if container '${{ env.TARGET_UPSTREAM }}' is running..."
-              
-              # 실행 중인 컨테이너 목록에서 TARGET_UPSTREAM 확인
-              if docker ps --format '{{.Names}}' | grep -q "^${{ env.TARGET_UPSTREAM }}$"; then
-                echo "✅ Success: Container '${{ env.TARGET_UPSTREAM }}' is running!"
-                exit 0
-              fi
-  
-              echo "⚠️ Container '${{ env.TARGET_UPSTREAM }}' is NOT running. Retrying in $RETRY_DELAY seconds..."
-              sleep $RETRY_DELAY
-              ATTEMPT=$((ATTEMPT+1))
-            done
-  
-            echo "❌ Error: Container '${{ env.TARGET_UPSTREAM }}' is still NOT running after $MAX_ATTEMPTS attempts!"
-            exit 1
+      - name: Set target IP based on running Docker container
+        run: |
+          ATTEMPT=0
+          MAX_ATTEMPTS=3
+          RETRY_DELAY=10  # 10초 대기
+      
+          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
+            echo "Attempt $((ATTEMPT+1)) - Checking if container '${{ env.TARGET_UPSTREAM }}' is running..."
+      
+            # 실행 중인 컨테이너 확인
+            EXIST_CONTAINER=$(docker ps --filter "name=${{ env.TARGET_UPSTREAM }}" --format "{{.Names}}")
+      
+            # 컨테이너가 실행 중이라면 exit 1
+            if [ -n "$EXIST_CONTAINER" ]; then
+              echo "⚠️ Container '${{ env.TARGET_UPSTREAM }}' is already running. Exiting with status 1."
+              exit 1
+            fi
+      
+            # 컨테이너가 실행 중이 아니면 계속해서 재시도
+            echo "${{ env.TARGET_UPSTREAM }} is NOT running -> Retrying in $RETRY_DELAY seconds..."
+            sleep $RETRY_DELAY
+            ATTEMPT=$((ATTEMPT+1))
+          done
+      
+          echo "❌ Error: Container '${{ env.TARGET_UPSTREAM }}' is still not running after $MAX_ATTEMPTS attempts!"
+          exit 1
 
 
 
